name: Build and Deploy to EC2

on:
  pull_request:
    types:
      - closed
    branches:
      - spring-release

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: spring-app:latest
          outputs: type=docker,dest=spring-app.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-app-image
          path: spring-app.tar

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: spring-app.tar
          target: /tmp

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Load the Docker image
            docker load -i /tmp/spring-app.tar
            
            # Stop and remove the existing container (if it exists)
            docker stop app-container || true
            docker rm app-container || true
            
            # Run the new container
            docker run -d --name app-container \
              -p 8080:8080 \
              --restart unless-stopped \
              spring-app:latest
            
            # Clean up
            rm /tmp/spring-app.tar
            docker system prune -af